### ISSUE TITLE
Cannot add avatar image.

### ISSUE THREAD

**Issue by artiya4u** [numaverse/numaverse-gateway#1]
Cannot add avatar image using a small jpeg file.
The response is "{status: 422, error: "Unprocessable Entity"}"
My image is below.
![3830524](https://user-images.githubusercontent.com/3830524/38252075-68e433ae-377d-11e8-884d-10fbc59dabf0.jpeg)

**Comment by hstove** [comment]
So sorry about that. I fixed the issue, should be good now. Thank you so much for checking out Numa and reaching out with your error. Sorry for the issues!
